version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ../environments/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app-backend
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ../environments/.env
    volumes:
      - ../src:/app/src
    command: "${MAIN_ARGS}"

volumes:
  postgres-data:
